// Generated by MSXgl on 2024-03-04 00:29:29
#pragma once
#include "core.h"

// Language definition
#define LANG_EN 0
#define LANG_FR 1
#define LANG_JA 2
#define LANG_MAX 3

// Text ID definition
#define TEXT_TITLE 0
#define TEXT_TITLE_TWITCH 1
#define TEXT_MAX 2

// Localization data table
const c8* const g_TransData[LANG_MAX][TEXT_MAX] =
{
	// EN
	{
		"MSXgl - Localization sample", // TEXT_TITLE
		"    THIS GAME IS MADE LIVE ON TWITCH", // TEXT_TITLE_TWITCH
	},
	// FR
	{
		"MSXgl - Sample de traduction", // TEXT_TITLE
		"    CE JEU EST FAIT\nEN LIVE SUR TWITCH", // TEXT_TITLE_TWITCH
	},
	// JA
	{
		"MSXgl - \xDB\xB0\xB6\xD8\xBE\xDE\xB0\xBC\xAE\xDD\xA5\xBB\xDD\xCC\xDF\xD9", // TEXT_TITLE
		"\x9A\xE9\x99\xDE\xB0\xF1\xEATwitch\xE3\xDE\xF7\x92\xEC\xDE\xEA\x92\x9C\xFD\x9B\xFA\xE3\x92\xEF\x9D", // TEXT_TITLE_TWITCH
	},
};