// Generated by MSXgl on 2025-01-12 14:55:55
#pragma once
#include "core.h"

// Language definition
#define LANG_EN 0
#define LANG_ES 1
#define LANG_FR 2
#define LANG_IT 3
#define LANG_JA 4
#define LANG_NL 5
#define LANG_PT_BR 6
#define LANG_TL 7
#define LANG_MAX 8

// Text ID definition
#define TEXT_LANG_LABEL 0
#define TEXT_TITLE 1
#define TEXT_TITLE_TWITCH 2
#define TEXT_PRESS_ESC 3
#define TEXT_ROOM1 4
#define TEXT_ROOM7 5
#define TEXT_ROOM11 6
#define TEXT_ROOM15 7
#define TEXT_ROOM19 8
#define TEXT_ROOM23 9
#define TEXT_ROOM25 10
#define TEXT_END_HOSPITAL 11
#define TEXT_END_ALIEN 12
#define TEXT_END_MATRIX 13
#define TEXT_THANKS 14
#define TEXT_MAX 15

// Localization data table
extern const c8* const g_TransData[LANG_MAX][TEXT_MAX];
