
#pragma once

// Numéros de tuile
#define TILE_EMPTY 0
#define TILE_RAILS 28
#define TILE_MANUAL_RAILS 35
#define TILE_PHONE 80
#define TILE_PHONE_ANIM_ONE 16
#define TILE_PHONE_ANIM_TWO 17
#define TILE_LIGHT1 81
#define TILE_LIGHT2 82
#define TILE_LOCK_DOOR1 12
#define TILE_LOCK_DOOR2 13
#define TILE_DOOR1 70
#define TILE_DOOR2 71
#define TILE_DOOR_NUMBER_ONE 1
#define TILE_DOOR_NUMBER_TWO 3
#define TILE_DOOR_NUMBER_THREE 5
#define TILE_CABLE 29
#define TILE_BROKEN_CABLE 83
#define TILE_FUSEBOX 84
#define TILE_FUSEBOX_ON 85
#define TILE_ELECTRIC_WALL 142
#define TILE_NOT_ELECTRIC_WALL 145
#define TILE_NIGHT_LIGHT 44
#define TILE_ALPHABET_ONE 209
#define TILE_MANUAL_ELEVATOR 184

// placard en anglais
#define TILE_CUPBOARD 67
#define TILE_CUPBOARD_UPPER_PART 25
#define TILE_CUPBOARD_OPEN 30
#define TILE_CLOSET 73 // placard en français
#define TILE_CLOSET_UPPER_PART 38

// Interrupteur Minuteur
#define TILE_SWITCH_TIMER 90

// Contrôle des ascenseurs
#define TILE_ELEVATOR_UP 87
#define TILE_ELEVATOR_DOWN 86

// Porte spéciale pour arriver à la fin du jeu
#define TILE_DOOR_END1 75
#define TILE_DOOR_END2 76

#define TILE_ITEM_KEY_CLOSET 96
#define TILE_ITEM_KEY_DOOR 97
#define TILE_ITEM_KEY_THREE 98
#define TILE_ITEM_FUSE 99
#define TILE_ITEM_TAPE 100

// tuiles spéciales de conditions
#define TILE_START_POS 127
#define TILE_SPE_LIGHT_OFF 125
#define TILE_SPE_LIGHT_ON 126
#define TILE_SPE_THEME_HOSPITAL 122
#define TILE_SPE_THEME_ALIEN 123
#define TILE_SPE_THEME_MATRIX 124
#define TILE_SPE_CUPBOARD 112
#define TILE_SPE_CUPBOARD_LIGHT 113
#define TILE_SPE_DISPLAY_TEXT 114
#define TILE_SPE_TRANSLATE 115
#define TILE_NUM_ZERO 208
#define TILE_SPE_TRANSLATE_PHONE 116

// Numéro de sprite
#define SPT_PLAYER_HAIR 0
#define SPT_PLAYER_SKIN 1
#define SPT_PLAYER_CHAIR 2
#define SPT_PLAYER_OUTLINE 16
#define SPT_ELEVATOR 3
